using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Adr.Cli.Extensions;
using Adr.Cli.Services;

using McpCore;

using Microsoft.Extensions.Logging;

namespace Adr.Cli.CommandHandlers;

public class ProjectPlanning : IProjectPlanning
{
    private readonly IAdrSettings settings;
    private readonly ILogger<AdrNew> logger;
    private readonly IAdrTasksRepository repository;
    private readonly IStdOut stdOut;
    private readonly IProcessHelper processHelper;

    public ProjectPlanning(
        IAdrSettings settings,
        ILogger<AdrNew> logger,
        IAdrTasksRepository repository,
        IStdOut stdOut,
        IProcessHelper processHelper)
    {
        this.settings = settings;
        this.logger = logger;
        this.repository = repository;
        this.stdOut = stdOut;
        this.processHelper = processHelper;
    }

    public async Task<Response> NewTaskAsync(string title, string description, string? dueDate)
    {
        if (!settings.TasksInitialized())
        {
            return Response.Fail($"Tasks folder is not initialized {settings.TasksFolderInfo().FullName}.");
        }

        Response result;
        logger.LogInformation($"Creating new tasks record.");
        result = await CreateTaskAsync(title, description, dueDate);
        return result;
    }

    private async Task<Response> CreateTaskAsync(string title, string description, string? dueDate)
    {
        if (!DateTime.TryParse(dueDate, out var date))
        {
            logger.LogWarning("Could not get due date from {StringValue}", dueDate);
        }

        var record = new TaskRecord
        {
            Title = title,
            Status = PlanningStatus.New,
            Description = description,
            DueDate = date
        };

        await repository.WriteRecordAsync(record);
        record.LaunchEditor(settings, processHelper);

        return Response.Ok($"Task is created in {settings.TasksFolder}.");
    }

    public async Task<Response> FindTasksAsync(string filter, PlanningStatus status, bool sortReverse, bool verbose, bool includeContent)
    {
        logger.LogDebug("Find tasks containing '{Filter}' {SortOrder}", filter, sortReverse ? "newest first" : "oldest first");

        var sb = new StringBuilder();
        var listMeta = new Dictionary<int, string>();
        var idList = FindRecordIds(0);
        var words = filter.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0)
        {
            sb.AppendLine("-- No filter provided --");
        }

        var items = idList.Distinct();
        if (sortReverse)
        {
            items = items.Reverse();
        }

        foreach (var recordId in items)
        {
            var showRecord = false;
            var adr = await repository.ReadMetadataAsync(recordId);
            if (adr == null)
            {
                continue;
            }

            foreach (var word in words)
            {
                if (adr.Title.Contains(word, StringComparison.OrdinalIgnoreCase))
                {
                    showRecord = true;
                    break;
                }
                if (!showRecord && adr.Description.Contains(word, StringComparison.OrdinalIgnoreCase))
                {
                    showRecord = true;
                    break;
                }
                if (!showRecord && includeContent)
                {
                    var content = await repository.ReadContentAsync(recordId);
                    if (content.Any(m => m.Contains(word, StringComparison.OrdinalIgnoreCase)))
                    {
                        showRecord = true;
                        break;
                    }
                }
            }

            if (showRecord)
            {
                var information = verbose
                    ? adr.VerboseString()
                    : adr.FormatString();
                listMeta.Add(adr.RecordId, information);
            }
        }

        foreach (var recordId in listMeta.Keys)
        {
            sb.AppendLine(listMeta[recordId]);
        }
        return Response.Ok(sb.ToString());
    }

    public async Task<Response> GeneratePlanningTocAsync()
    {
        var toc = new StringBuilder();
        var projectName = settings.ProjectName;

        // Add file description
        toc.AppendLine($"# {projectName}");
        toc.AppendLine();
        toc.AppendLine($"__Date__ : {DateTime.Now:F}");
        toc.AppendLine();
        toc.AppendLine("This file contains the table of contents for the open tasks.");
        toc.AppendLine("It is auto generated by the adr-cli tool, any manual modifications are overwritten.");
        toc.AppendLine();

        // Add table header
        toc.AppendLine("# Current open tasks:");
        toc.AppendLine();
        toc.AppendLine("| Adr | Title | Status | Due date |");
        toc.AppendLine("| --- | ----- | ------ | -------- |");

        // Add table content
        var docFolder = settings.TasksFolderInfo();
        foreach (var docInfo in docFolder.EnumerateFiles("*.md").OrderBy(x => x.Name))
        {
            var recordIdPart = docInfo.Name.Split('-')[0];
            if (int.TryParse(recordIdPart, out var recordId))
            {
                var record = await repository.ReadMetadataAsync(recordId);
                if (record == null)
                {
                    continue;
                }

                // only relevant tasks
                if (Constants.InactiveStatusList.Contains(record.Status))
                {
                    continue;
                }

                var link = $"..\\{settings.TasksFolder}\\{record.FileName}.md";
                toc.AppendLine($"| {record.RecordId} | [{record.Title}]({link}) | {record.Status} | {record.DueDate} |");
            }
        }
        toc.AppendLine();

        var (success, generatedFile) = await repository.CreateRootDocumentAsync("tasks-toc.md", toc);

        return success
            ? Response.Ok($"Generated Tasks overview in {generatedFile}.")
            : Response.Fail($"Generating Tasks overview in {generatedFile} is not completed.");
    }

    public async Task<Response> ListTasksAsync(bool sortReverse, bool verbose)
    {
        logger.LogDebug("List ADR {SortOrder}", sortReverse ? "newest first" : "oldest first");

        var listMeta = new Dictionary<int, string>();
        var idList = FindRecordIds(0);

        var items = idList.Distinct();
        if (sortReverse)
        {
            items = items.Reverse();
        }

        foreach (var recordId in items)
        {
            var adr = await repository.ReadMetadataAsync(recordId);
            if (adr == null)
            {
                continue;
            }

            var information = verbose
                ? adr.VerboseString()
                : adr.FormatString();
            listMeta.Add(adr.RecordId, information);
        }

        var sb = new StringBuilder();
        foreach (var recordId in listMeta.Keys)
        {
            sb.AppendLine(listMeta[recordId]);
        }
        return Response.Ok(sb.ToString());
    }

    private List<int> FindRecordIds(int startFromRecord)
    {
        var dir = settings.TasksFolderInfo();
        var metadataFiles = dir.EnumerateFiles("*.md").Select(m => m.Name);
        var idList = new List<int>();
        foreach (var metadataFile in metadataFiles)
        {
            var parts = metadataFile.Split('-');
            if (parts.Length < 1)
            {
                continue;
            }

            if (int.TryParse(parts[0], out var recordId) && recordId >= startFromRecord)
            {
                idList.Add(recordId);
            }
        }

        return idList;
    }

    public async Task<Response> LinkTaskAsync(int sourceId, int targetId, string remark)
    {
        var source = await repository.ReadMetadataAsync(sourceId);
        if (source == null)
        {
            return Response.Fail($"Could not find source record with id {sourceId}");
        }

        var target = await repository.ReadMetadataAsync(targetId);
        if (target == null)
        {
            return Response.Fail($"Could not find target record with id {targetId}");
        }

        if (source.Related.ContainsKey(targetId))
        {
            return Response.Fail($"Task '{source.Title}' is already related to '{target.Title}'.");
        }
        source.Related[targetId] = target.Title;
        source.Logs.Add(new StatusUpdate { DateTime = DateTime.UtcNow, Status = PlanningStatus.Related, Justification = remark });

        var updateCount = await repository.UpdateMetadataAsync(sourceId, source);

        return updateCount < 0
            ? Response.Fail($"Could not update task '{source.Title}' with Id:{sourceId}")
            : updateCount > 0 ? Response.Ok($"Task '{source.Title}' with Id:{sourceId} is now linked to task '{target.Title}' with Id:{targetId}")
            : Response.Fail($"Task '{source.Title}' with Id:{sourceId} is not modified.");
    }

    public async Task<Response> RemoveTaskLinkAsync(int sourceId, int targetId)
    {
        var source = await repository.ReadMetadataAsync(sourceId);
        if (source == null)
        {
            return Response.Fail($"Could not find source record with id {sourceId}");
        }

        if (!source.Related.ContainsKey(targetId))
        {
            return Response.Fail($"Task '{source.Title}' is not related to a task with Id:{targetId}.");
        }
        source.Related.Remove(targetId);

        var updateCount = await repository.UpdateMetadataAsync(sourceId, source);
        return updateCount < 0
            ? Response.Fail($"Could not update task '{source.Title}' with Id:{sourceId}")
            : updateCount > 0 ? Response.Ok($"Task '{source.Title}' with Id:{sourceId} is modified, the relation to task with Id:{targetId} is removed.")
            : Response.Fail($"Task '{source.Title}' with Id:{sourceId} is not modified.");
    }

    public async Task<Response> UpdateTaskAsync(string sourceId, PlanningStatus status, string justification)
    {
        if (!int.TryParse(sourceId, out var id))
        {
            return Response.Fail($"Could not get valid record id from {sourceId}");
        }
        var record = await repository.ReadMetadataAsync(id);
        if (record == null)
        {
            return Response.Fail($"Could not find record with id {sourceId}");
        }
        record.Status = status;
        record.Logs.Add(new StatusUpdate { DateTime = DateTime.UtcNow, Status = status, Justification = justification });
        var updateCount = await repository.UpdateMetadataAsync(id, record);

        return updateCount < 0
            ? Response.Fail($"Could not update task '{record.Title}' with Id:{id} current status is {record.Status}")
            : updateCount > 0 ? Response.Ok($"Task '{record.Title}' with Id:{id} has a new status: {record.Status}")
            : Response.Fail($"No status update for task '{record.Title}' with Id:{id} current status is {record.Status}");
    }
}